# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Converter.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'Converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x43onverter.proto\x12\tConverter\".\n\tFileChunk\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\",\n\nParsedText\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2K\n\tConverter\x12>\n\x0b\x43onvertFile\x12\x14.Converter.FileChunk\x1a\x15.Converter.ParsedText(\x01\x30\x01\x42\rZ\x0b/;Converterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013/;Converter'
  _globals['_FILECHUNK']._serialized_start=30
  _globals['_FILECHUNK']._serialized_end=76
  _globals['_PARSEDTEXT']._serialized_start=78
  _globals['_PARSEDTEXT']._serialized_end=122
  _globals['_CONVERTER']._serialized_start=124
  _globals['_CONVERTER']._serialized_end=199
# @@protoc_insertion_point(module_scope)
