// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AnswerReceive.proto
// Protobuf C++ Version: 5.29.3

#include "AnswerReceive.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace AnswerReceive {

inline constexpr UploadResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UploadResponse::UploadResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UploadResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UploadResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UploadResponseDefaultTypeInternal() {}
  union {
    UploadResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UploadResponseDefaultTypeInternal _UploadResponse_default_instance_;

inline constexpr Query::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : query_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Query::Query(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct QueryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QueryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QueryDefaultTypeInternal() {}
  union {
    Query _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QueryDefaultTypeInternal _Query_default_instance_;

inline constexpr FilesCount::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filescount_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FilesCount::FilesCount(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FilesCountDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FilesCountDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FilesCountDefaultTypeInternal() {}
  union {
    FilesCount _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FilesCountDefaultTypeInternal _FilesCount_default_instance_;

inline constexpr FileMatch::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rank_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileMatch::FileMatch(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileMatchDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileMatchDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileMatchDefaultTypeInternal() {}
  union {
    FileMatch _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileMatchDefaultTypeInternal _FileMatch_default_instance_;

inline constexpr FileFrequency::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        frequency_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileFrequency::FileFrequency(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileFrequencyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileFrequencyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileFrequencyDefaultTypeInternal() {}
  union {
    FileFrequency _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileFrequencyDefaultTypeInternal _FileFrequency_default_instance_;

inline constexpr WordEntry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : files_{},
        word_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WordEntry::WordEntry(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WordEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WordEntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WordEntryDefaultTypeInternal() {}
  union {
    WordEntry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WordEntryDefaultTypeInternal _WordEntry_default_instance_;

inline constexpr QueryResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : matches_{},
        query_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR QueryResult::QueryResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct QueryResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QueryResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QueryResultDefaultTypeInternal() {}
  union {
    QueryResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QueryResultDefaultTypeInternal _QueryResult_default_instance_;
}  // namespace AnswerReceive
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_AnswerReceive_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_AnswerReceive_2eproto = nullptr;
const ::uint32_t
    TableStruct_AnswerReceive_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::WordEntry, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::WordEntry, _impl_.word_),
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::WordEntry, _impl_.files_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::FilesCount, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::FilesCount, _impl_.filescount_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::FileFrequency, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::FileFrequency, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::FileFrequency, _impl_.frequency_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::UploadResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::UploadResponse, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::Query, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::Query, _impl_.query_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::QueryResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::QueryResult, _impl_.query_),
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::QueryResult, _impl_.matches_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::FileMatch, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::FileMatch, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::AnswerReceive::FileMatch, _impl_.rank_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::AnswerReceive::WordEntry)},
        {10, -1, -1, sizeof(::AnswerReceive::FilesCount)},
        {19, -1, -1, sizeof(::AnswerReceive::FileFrequency)},
        {29, -1, -1, sizeof(::AnswerReceive::UploadResponse)},
        {38, -1, -1, sizeof(::AnswerReceive::Query)},
        {47, -1, -1, sizeof(::AnswerReceive::QueryResult)},
        {57, -1, -1, sizeof(::AnswerReceive::FileMatch)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::AnswerReceive::_WordEntry_default_instance_._instance,
    &::AnswerReceive::_FilesCount_default_instance_._instance,
    &::AnswerReceive::_FileFrequency_default_instance_._instance,
    &::AnswerReceive::_UploadResponse_default_instance_._instance,
    &::AnswerReceive::_Query_default_instance_._instance,
    &::AnswerReceive::_QueryResult_default_instance_._instance,
    &::AnswerReceive::_FileMatch_default_instance_._instance,
};
const char descriptor_table_protodef_AnswerReceive_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023AnswerReceive.proto\022\rAnswerReceive\"F\n\t"
    "WordEntry\022\014\n\004word\030\001 \001(\t\022+\n\005files\030\002 \003(\0132\034"
    ".AnswerReceive.FileFrequency\" \n\nFilesCou"
    "nt\022\022\n\nfilesCount\030\002 \001(\005\"4\n\rFileFrequency\022"
    "\020\n\010filename\030\001 \001(\t\022\021\n\tfrequency\030\002 \001(\005\"!\n\016"
    "UploadResponse\022\017\n\007message\030\001 \001(\t\"\026\n\005Query"
    "\022\r\n\005query\030\001 \001(\t\"G\n\013QueryResult\022\r\n\005query\030"
    "\001 \001(\t\022)\n\007matches\030\002 \003(\0132\030.AnswerReceive.F"
    "ileMatch\"+\n\tFileMatch\022\020\n\010filename\030\001 \001(\t\022"
    "\014\n\004rank\030\002 \001(\0022\345\001\n\nDictionary\022J\n\016SendFile"
    "sCount\022\031.AnswerReceive.FilesCount\032\035.Answ"
    "erReceive.UploadResponse\022K\n\016SendDictiona"
    "ry\022\030.AnswerReceive.WordEntry\032\035.AnswerRec"
    "eive.UploadResponse(\001\022>\n\006Search\022\024.Answer"
    "Receive.Query\032\032.AnswerReceive.QueryResul"
    "t(\0010\001B\021Z\017/;AnswerReceiveb\006proto3"
};
static ::absl::once_flag descriptor_table_AnswerReceive_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_AnswerReceive_2eproto = {
    false,
    false,
    632,
    descriptor_table_protodef_AnswerReceive_2eproto,
    "AnswerReceive.proto",
    &descriptor_table_AnswerReceive_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_AnswerReceive_2eproto::offsets,
    file_level_enum_descriptors_AnswerReceive_2eproto,
    file_level_service_descriptors_AnswerReceive_2eproto,
};
namespace AnswerReceive {
// ===================================================================

class WordEntry::_Internal {
 public:
};

WordEntry::WordEntry(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnswerReceive.WordEntry)
}
inline PROTOBUF_NDEBUG_INLINE WordEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::AnswerReceive::WordEntry& from_msg)
      : files_{visibility, arena, from.files_},
        word_(arena, from.word_),
        _cached_size_{0} {}

WordEntry::WordEntry(
    ::google::protobuf::Arena* arena,
    const WordEntry& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WordEntry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:AnswerReceive.WordEntry)
}
inline PROTOBUF_NDEBUG_INLINE WordEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : files_{visibility, arena},
        word_(arena),
        _cached_size_{0} {}

inline void WordEntry::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
WordEntry::~WordEntry() {
  // @@protoc_insertion_point(destructor:AnswerReceive.WordEntry)
  SharedDtor(*this);
}
inline void WordEntry::SharedDtor(MessageLite& self) {
  WordEntry& this_ = static_cast<WordEntry&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.word_.Destroy();
  this_._impl_.~Impl_();
}

inline void* WordEntry::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) WordEntry(arena);
}
constexpr auto WordEntry::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(WordEntry, _impl_.files_) +
          decltype(WordEntry::_impl_.files_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(WordEntry), alignof(WordEntry), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&WordEntry::PlacementNew_,
                                 sizeof(WordEntry),
                                 alignof(WordEntry));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull WordEntry::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_WordEntry_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &WordEntry::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<WordEntry>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &WordEntry::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<WordEntry>(), &WordEntry::ByteSizeLong,
            &WordEntry::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(WordEntry, _impl_._cached_size_),
        false,
    },
    &WordEntry::kDescriptorMethods,
    &descriptor_table_AnswerReceive_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* WordEntry::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 36, 2> WordEntry::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnswerReceive::WordEntry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .AnswerReceive.FileFrequency files = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(WordEntry, _impl_.files_)}},
    // string word = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(WordEntry, _impl_.word_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string word = 1;
    {PROTOBUF_FIELD_OFFSET(WordEntry, _impl_.word_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .AnswerReceive.FileFrequency files = 2;
    {PROTOBUF_FIELD_OFFSET(WordEntry, _impl_.files_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::AnswerReceive::FileFrequency>()},
  }}, {{
    "\27\4\0\0\0\0\0\0"
    "AnswerReceive.WordEntry"
    "word"
  }},
};

PROTOBUF_NOINLINE void WordEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:AnswerReceive.WordEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.files_.Clear();
  _impl_.word_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WordEntry::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WordEntry& this_ = static_cast<const WordEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WordEntry::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WordEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:AnswerReceive.WordEntry)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string word = 1;
          if (!this_._internal_word().empty()) {
            const std::string& _s = this_._internal_word();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AnswerReceive.WordEntry.word");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // repeated .AnswerReceive.FileFrequency files = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_files_size());
               i < n; i++) {
            const auto& repfield = this_._internal_files().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:AnswerReceive.WordEntry)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WordEntry::ByteSizeLong(const MessageLite& base) {
          const WordEntry& this_ = static_cast<const WordEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WordEntry::ByteSizeLong() const {
          const WordEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:AnswerReceive.WordEntry)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .AnswerReceive.FileFrequency files = 2;
            {
              total_size += 1UL * this_._internal_files_size();
              for (const auto& msg : this_._internal_files()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string word = 1;
            if (!this_._internal_word().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_word());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WordEntry::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WordEntry*>(&to_msg);
  auto& from = static_cast<const WordEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnswerReceive.WordEntry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_files()->MergeFrom(
      from._internal_files());
  if (!from._internal_word().empty()) {
    _this->_internal_set_word(from._internal_word());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WordEntry::CopyFrom(const WordEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnswerReceive.WordEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WordEntry::InternalSwap(WordEntry* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.files_.InternalSwap(&other->_impl_.files_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.word_, &other->_impl_.word_, arena);
}

::google::protobuf::Metadata WordEntry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FilesCount::_Internal {
 public:
};

FilesCount::FilesCount(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnswerReceive.FilesCount)
}
FilesCount::FilesCount(
    ::google::protobuf::Arena* arena, const FilesCount& from)
    : FilesCount(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE FilesCount::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FilesCount::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.filescount_ = {};
}
FilesCount::~FilesCount() {
  // @@protoc_insertion_point(destructor:AnswerReceive.FilesCount)
  SharedDtor(*this);
}
inline void FilesCount::SharedDtor(MessageLite& self) {
  FilesCount& this_ = static_cast<FilesCount&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* FilesCount::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FilesCount(arena);
}
constexpr auto FilesCount::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(FilesCount),
                                            alignof(FilesCount));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FilesCount::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FilesCount_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FilesCount::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FilesCount>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FilesCount::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FilesCount>(), &FilesCount::ByteSizeLong,
            &FilesCount::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FilesCount, _impl_._cached_size_),
        false,
    },
    &FilesCount::kDescriptorMethods,
    &descriptor_table_AnswerReceive_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FilesCount::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> FilesCount::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnswerReceive::FilesCount>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 filesCount = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FilesCount, _impl_.filescount_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FilesCount, _impl_.filescount_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 filesCount = 2;
    {PROTOBUF_FIELD_OFFSET(FilesCount, _impl_.filescount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void FilesCount::Clear() {
// @@protoc_insertion_point(message_clear_start:AnswerReceive.FilesCount)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filescount_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FilesCount::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FilesCount& this_ = static_cast<const FilesCount&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FilesCount::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FilesCount& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:AnswerReceive.FilesCount)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 filesCount = 2;
          if (this_._internal_filescount() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_filescount(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:AnswerReceive.FilesCount)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FilesCount::ByteSizeLong(const MessageLite& base) {
          const FilesCount& this_ = static_cast<const FilesCount&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FilesCount::ByteSizeLong() const {
          const FilesCount& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:AnswerReceive.FilesCount)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 filesCount = 2;
            if (this_._internal_filescount() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_filescount());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FilesCount::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FilesCount*>(&to_msg);
  auto& from = static_cast<const FilesCount&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnswerReceive.FilesCount)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_filescount() != 0) {
    _this->_impl_.filescount_ = from._impl_.filescount_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FilesCount::CopyFrom(const FilesCount& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnswerReceive.FilesCount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FilesCount::InternalSwap(FilesCount* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.filescount_, other->_impl_.filescount_);
}

::google::protobuf::Metadata FilesCount::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileFrequency::_Internal {
 public:
};

FileFrequency::FileFrequency(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnswerReceive.FileFrequency)
}
inline PROTOBUF_NDEBUG_INLINE FileFrequency::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::AnswerReceive::FileFrequency& from_msg)
      : filename_(arena, from.filename_),
        _cached_size_{0} {}

FileFrequency::FileFrequency(
    ::google::protobuf::Arena* arena,
    const FileFrequency& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileFrequency* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.frequency_ = from._impl_.frequency_;

  // @@protoc_insertion_point(copy_constructor:AnswerReceive.FileFrequency)
}
inline PROTOBUF_NDEBUG_INLINE FileFrequency::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        _cached_size_{0} {}

inline void FileFrequency::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.frequency_ = {};
}
FileFrequency::~FileFrequency() {
  // @@protoc_insertion_point(destructor:AnswerReceive.FileFrequency)
  SharedDtor(*this);
}
inline void FileFrequency::SharedDtor(MessageLite& self) {
  FileFrequency& this_ = static_cast<FileFrequency&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* FileFrequency::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FileFrequency(arena);
}
constexpr auto FileFrequency::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FileFrequency),
                                            alignof(FileFrequency));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FileFrequency::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FileFrequency_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FileFrequency::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FileFrequency>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FileFrequency::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FileFrequency>(), &FileFrequency::ByteSizeLong,
            &FileFrequency::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FileFrequency, _impl_._cached_size_),
        false,
    },
    &FileFrequency::kDescriptorMethods,
    &descriptor_table_AnswerReceive_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FileFrequency::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 44, 2> FileFrequency::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnswerReceive::FileFrequency>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 frequency = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileFrequency, _impl_.frequency_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FileFrequency, _impl_.frequency_)}},
    // string filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileFrequency, _impl_.filename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string filename = 1;
    {PROTOBUF_FIELD_OFFSET(FileFrequency, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 frequency = 2;
    {PROTOBUF_FIELD_OFFSET(FileFrequency, _impl_.frequency_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\33\10\0\0\0\0\0\0"
    "AnswerReceive.FileFrequency"
    "filename"
  }},
};

PROTOBUF_NOINLINE void FileFrequency::Clear() {
// @@protoc_insertion_point(message_clear_start:AnswerReceive.FileFrequency)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  _impl_.frequency_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FileFrequency::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FileFrequency& this_ = static_cast<const FileFrequency&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FileFrequency::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FileFrequency& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:AnswerReceive.FileFrequency)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string filename = 1;
          if (!this_._internal_filename().empty()) {
            const std::string& _s = this_._internal_filename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AnswerReceive.FileFrequency.filename");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 frequency = 2;
          if (this_._internal_frequency() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_frequency(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:AnswerReceive.FileFrequency)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FileFrequency::ByteSizeLong(const MessageLite& base) {
          const FileFrequency& this_ = static_cast<const FileFrequency&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FileFrequency::ByteSizeLong() const {
          const FileFrequency& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:AnswerReceive.FileFrequency)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string filename = 1;
            if (!this_._internal_filename().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_filename());
            }
            // int32 frequency = 2;
            if (this_._internal_frequency() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_frequency());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FileFrequency::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileFrequency*>(&to_msg);
  auto& from = static_cast<const FileFrequency&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnswerReceive.FileFrequency)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (from._internal_frequency() != 0) {
    _this->_impl_.frequency_ = from._impl_.frequency_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileFrequency::CopyFrom(const FileFrequency& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnswerReceive.FileFrequency)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileFrequency::InternalSwap(FileFrequency* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
        swap(_impl_.frequency_, other->_impl_.frequency_);
}

::google::protobuf::Metadata FileFrequency::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UploadResponse::_Internal {
 public:
};

UploadResponse::UploadResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnswerReceive.UploadResponse)
}
inline PROTOBUF_NDEBUG_INLINE UploadResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::AnswerReceive::UploadResponse& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

UploadResponse::UploadResponse(
    ::google::protobuf::Arena* arena,
    const UploadResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UploadResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:AnswerReceive.UploadResponse)
}
inline PROTOBUF_NDEBUG_INLINE UploadResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void UploadResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UploadResponse::~UploadResponse() {
  // @@protoc_insertion_point(destructor:AnswerReceive.UploadResponse)
  SharedDtor(*this);
}
inline void UploadResponse::SharedDtor(MessageLite& self) {
  UploadResponse& this_ = static_cast<UploadResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UploadResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UploadResponse(arena);
}
constexpr auto UploadResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UploadResponse),
                                            alignof(UploadResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UploadResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UploadResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UploadResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UploadResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UploadResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UploadResponse>(), &UploadResponse::ByteSizeLong,
            &UploadResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UploadResponse, _impl_._cached_size_),
        false,
    },
    &UploadResponse::kDescriptorMethods,
    &descriptor_table_AnswerReceive_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UploadResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 44, 2> UploadResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnswerReceive::UploadResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UploadResponse, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(UploadResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\7\0\0\0\0\0\0"
    "AnswerReceive.UploadResponse"
    "message"
  }},
};

PROTOBUF_NOINLINE void UploadResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:AnswerReceive.UploadResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UploadResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UploadResponse& this_ = static_cast<const UploadResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UploadResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UploadResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:AnswerReceive.UploadResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string message = 1;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AnswerReceive.UploadResponse.message");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:AnswerReceive.UploadResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UploadResponse::ByteSizeLong(const MessageLite& base) {
          const UploadResponse& this_ = static_cast<const UploadResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UploadResponse::ByteSizeLong() const {
          const UploadResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:AnswerReceive.UploadResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string message = 1;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UploadResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UploadResponse*>(&to_msg);
  auto& from = static_cast<const UploadResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnswerReceive.UploadResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UploadResponse::CopyFrom(const UploadResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnswerReceive.UploadResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UploadResponse::InternalSwap(UploadResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata UploadResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Query::_Internal {
 public:
};

Query::Query(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnswerReceive.Query)
}
inline PROTOBUF_NDEBUG_INLINE Query::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::AnswerReceive::Query& from_msg)
      : query_(arena, from.query_),
        _cached_size_{0} {}

Query::Query(
    ::google::protobuf::Arena* arena,
    const Query& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Query* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:AnswerReceive.Query)
}
inline PROTOBUF_NDEBUG_INLINE Query::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : query_(arena),
        _cached_size_{0} {}

inline void Query::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Query::~Query() {
  // @@protoc_insertion_point(destructor:AnswerReceive.Query)
  SharedDtor(*this);
}
inline void Query::SharedDtor(MessageLite& self) {
  Query& this_ = static_cast<Query&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.query_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Query::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Query(arena);
}
constexpr auto Query::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Query),
                                            alignof(Query));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Query::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Query_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Query::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Query>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Query::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Query>(), &Query::ByteSizeLong,
            &Query::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Query, _impl_._cached_size_),
        false,
    },
    &Query::kDescriptorMethods,
    &descriptor_table_AnswerReceive_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Query::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2> Query::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnswerReceive::Query>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string query = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Query, _impl_.query_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string query = 1;
    {PROTOBUF_FIELD_OFFSET(Query, _impl_.query_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\5\0\0\0\0\0\0"
    "AnswerReceive.Query"
    "query"
  }},
};

PROTOBUF_NOINLINE void Query::Clear() {
// @@protoc_insertion_point(message_clear_start:AnswerReceive.Query)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.query_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Query::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Query& this_ = static_cast<const Query&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Query::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Query& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:AnswerReceive.Query)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string query = 1;
          if (!this_._internal_query().empty()) {
            const std::string& _s = this_._internal_query();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AnswerReceive.Query.query");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:AnswerReceive.Query)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Query::ByteSizeLong(const MessageLite& base) {
          const Query& this_ = static_cast<const Query&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Query::ByteSizeLong() const {
          const Query& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:AnswerReceive.Query)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string query = 1;
            if (!this_._internal_query().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_query());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Query::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Query*>(&to_msg);
  auto& from = static_cast<const Query&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnswerReceive.Query)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_query().empty()) {
    _this->_internal_set_query(from._internal_query());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Query::CopyFrom(const Query& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnswerReceive.Query)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Query::InternalSwap(Query* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.query_, &other->_impl_.query_, arena);
}

::google::protobuf::Metadata Query::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class QueryResult::_Internal {
 public:
};

QueryResult::QueryResult(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnswerReceive.QueryResult)
}
inline PROTOBUF_NDEBUG_INLINE QueryResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::AnswerReceive::QueryResult& from_msg)
      : matches_{visibility, arena, from.matches_},
        query_(arena, from.query_),
        _cached_size_{0} {}

QueryResult::QueryResult(
    ::google::protobuf::Arena* arena,
    const QueryResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  QueryResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:AnswerReceive.QueryResult)
}
inline PROTOBUF_NDEBUG_INLINE QueryResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : matches_{visibility, arena},
        query_(arena),
        _cached_size_{0} {}

inline void QueryResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
QueryResult::~QueryResult() {
  // @@protoc_insertion_point(destructor:AnswerReceive.QueryResult)
  SharedDtor(*this);
}
inline void QueryResult::SharedDtor(MessageLite& self) {
  QueryResult& this_ = static_cast<QueryResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.query_.Destroy();
  this_._impl_.~Impl_();
}

inline void* QueryResult::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) QueryResult(arena);
}
constexpr auto QueryResult::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(QueryResult, _impl_.matches_) +
          decltype(QueryResult::_impl_.matches_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(QueryResult), alignof(QueryResult), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&QueryResult::PlacementNew_,
                                 sizeof(QueryResult),
                                 alignof(QueryResult));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull QueryResult::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_QueryResult_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &QueryResult::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<QueryResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &QueryResult::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<QueryResult>(), &QueryResult::ByteSizeLong,
            &QueryResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(QueryResult, _impl_._cached_size_),
        false,
    },
    &QueryResult::kDescriptorMethods,
    &descriptor_table_AnswerReceive_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* QueryResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 39, 2> QueryResult::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnswerReceive::QueryResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .AnswerReceive.FileMatch matches = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(QueryResult, _impl_.matches_)}},
    // string query = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(QueryResult, _impl_.query_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string query = 1;
    {PROTOBUF_FIELD_OFFSET(QueryResult, _impl_.query_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .AnswerReceive.FileMatch matches = 2;
    {PROTOBUF_FIELD_OFFSET(QueryResult, _impl_.matches_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::AnswerReceive::FileMatch>()},
  }}, {{
    "\31\5\0\0\0\0\0\0"
    "AnswerReceive.QueryResult"
    "query"
  }},
};

PROTOBUF_NOINLINE void QueryResult::Clear() {
// @@protoc_insertion_point(message_clear_start:AnswerReceive.QueryResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.matches_.Clear();
  _impl_.query_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* QueryResult::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const QueryResult& this_ = static_cast<const QueryResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* QueryResult::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const QueryResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:AnswerReceive.QueryResult)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string query = 1;
          if (!this_._internal_query().empty()) {
            const std::string& _s = this_._internal_query();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AnswerReceive.QueryResult.query");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // repeated .AnswerReceive.FileMatch matches = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_matches_size());
               i < n; i++) {
            const auto& repfield = this_._internal_matches().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:AnswerReceive.QueryResult)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t QueryResult::ByteSizeLong(const MessageLite& base) {
          const QueryResult& this_ = static_cast<const QueryResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t QueryResult::ByteSizeLong() const {
          const QueryResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:AnswerReceive.QueryResult)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .AnswerReceive.FileMatch matches = 2;
            {
              total_size += 1UL * this_._internal_matches_size();
              for (const auto& msg : this_._internal_matches()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string query = 1;
            if (!this_._internal_query().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_query());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void QueryResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<QueryResult*>(&to_msg);
  auto& from = static_cast<const QueryResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnswerReceive.QueryResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_matches()->MergeFrom(
      from._internal_matches());
  if (!from._internal_query().empty()) {
    _this->_internal_set_query(from._internal_query());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void QueryResult::CopyFrom(const QueryResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnswerReceive.QueryResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void QueryResult::InternalSwap(QueryResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.matches_.InternalSwap(&other->_impl_.matches_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.query_, &other->_impl_.query_, arena);
}

::google::protobuf::Metadata QueryResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileMatch::_Internal {
 public:
};

FileMatch::FileMatch(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnswerReceive.FileMatch)
}
inline PROTOBUF_NDEBUG_INLINE FileMatch::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::AnswerReceive::FileMatch& from_msg)
      : filename_(arena, from.filename_),
        _cached_size_{0} {}

FileMatch::FileMatch(
    ::google::protobuf::Arena* arena,
    const FileMatch& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileMatch* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.rank_ = from._impl_.rank_;

  // @@protoc_insertion_point(copy_constructor:AnswerReceive.FileMatch)
}
inline PROTOBUF_NDEBUG_INLINE FileMatch::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        _cached_size_{0} {}

inline void FileMatch::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rank_ = {};
}
FileMatch::~FileMatch() {
  // @@protoc_insertion_point(destructor:AnswerReceive.FileMatch)
  SharedDtor(*this);
}
inline void FileMatch::SharedDtor(MessageLite& self) {
  FileMatch& this_ = static_cast<FileMatch&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* FileMatch::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FileMatch(arena);
}
constexpr auto FileMatch::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FileMatch),
                                            alignof(FileMatch));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FileMatch::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FileMatch_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FileMatch::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FileMatch>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FileMatch::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FileMatch>(), &FileMatch::ByteSizeLong,
            &FileMatch::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FileMatch, _impl_._cached_size_),
        false,
    },
    &FileMatch::kDescriptorMethods,
    &descriptor_table_AnswerReceive_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FileMatch::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2> FileMatch::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnswerReceive::FileMatch>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float rank = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(FileMatch, _impl_.rank_)}},
    // string filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileMatch, _impl_.filename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string filename = 1;
    {PROTOBUF_FIELD_OFFSET(FileMatch, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float rank = 2;
    {PROTOBUF_FIELD_OFFSET(FileMatch, _impl_.rank_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
    "\27\10\0\0\0\0\0\0"
    "AnswerReceive.FileMatch"
    "filename"
  }},
};

PROTOBUF_NOINLINE void FileMatch::Clear() {
// @@protoc_insertion_point(message_clear_start:AnswerReceive.FileMatch)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  _impl_.rank_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FileMatch::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FileMatch& this_ = static_cast<const FileMatch&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FileMatch::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FileMatch& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:AnswerReceive.FileMatch)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string filename = 1;
          if (!this_._internal_filename().empty()) {
            const std::string& _s = this_._internal_filename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AnswerReceive.FileMatch.filename");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // float rank = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_rank()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_rank(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:AnswerReceive.FileMatch)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FileMatch::ByteSizeLong(const MessageLite& base) {
          const FileMatch& this_ = static_cast<const FileMatch&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FileMatch::ByteSizeLong() const {
          const FileMatch& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:AnswerReceive.FileMatch)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string filename = 1;
            if (!this_._internal_filename().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_filename());
            }
            // float rank = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_rank()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FileMatch::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileMatch*>(&to_msg);
  auto& from = static_cast<const FileMatch&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnswerReceive.FileMatch)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_rank()) != 0) {
    _this->_impl_.rank_ = from._impl_.rank_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileMatch::CopyFrom(const FileMatch& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnswerReceive.FileMatch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileMatch::InternalSwap(FileMatch* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
        swap(_impl_.rank_, other->_impl_.rank_);
}

::google::protobuf::Metadata FileMatch::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace AnswerReceive
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_AnswerReceive_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
