// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: InvertedIndex.proto

package InvertedIndex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvertedIndex_BuildIndex_FullMethodName = "/InvertedIndex.InvertedIndex/BuildIndex"
)

// InvertedIndexClient is the client API for InvertedIndex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvertedIndexClient interface {
	BuildIndex(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IndexRequest, IndexResponse], error)
}

type invertedIndexClient struct {
	cc grpc.ClientConnInterface
}

func NewInvertedIndexClient(cc grpc.ClientConnInterface) InvertedIndexClient {
	return &invertedIndexClient{cc}
}

func (c *invertedIndexClient) BuildIndex(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IndexRequest, IndexResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InvertedIndex_ServiceDesc.Streams[0], InvertedIndex_BuildIndex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IndexRequest, IndexResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InvertedIndex_BuildIndexClient = grpc.ClientStreamingClient[IndexRequest, IndexResponse]

// InvertedIndexServer is the server API for InvertedIndex service.
// All implementations must embed UnimplementedInvertedIndexServer
// for forward compatibility.
type InvertedIndexServer interface {
	BuildIndex(grpc.ClientStreamingServer[IndexRequest, IndexResponse]) error
	mustEmbedUnimplementedInvertedIndexServer()
}

// UnimplementedInvertedIndexServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvertedIndexServer struct{}

func (UnimplementedInvertedIndexServer) BuildIndex(grpc.ClientStreamingServer[IndexRequest, IndexResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BuildIndex not implemented")
}
func (UnimplementedInvertedIndexServer) mustEmbedUnimplementedInvertedIndexServer() {}
func (UnimplementedInvertedIndexServer) testEmbeddedByValue()                       {}

// UnsafeInvertedIndexServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvertedIndexServer will
// result in compilation errors.
type UnsafeInvertedIndexServer interface {
	mustEmbedUnimplementedInvertedIndexServer()
}

func RegisterInvertedIndexServer(s grpc.ServiceRegistrar, srv InvertedIndexServer) {
	// If the following call pancis, it indicates UnimplementedInvertedIndexServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvertedIndex_ServiceDesc, srv)
}

func _InvertedIndex_BuildIndex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InvertedIndexServer).BuildIndex(&grpc.GenericServerStream[IndexRequest, IndexResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InvertedIndex_BuildIndexServer = grpc.ClientStreamingServer[IndexRequest, IndexResponse]

// InvertedIndex_ServiceDesc is the grpc.ServiceDesc for InvertedIndex service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvertedIndex_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "InvertedIndex.InvertedIndex",
	HandlerType: (*InvertedIndexServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BuildIndex",
			Handler:       _InvertedIndex_BuildIndex_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "InvertedIndex.proto",
}
