// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: InvertedIndex.proto

package InvertedIndex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_InvertedIndex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InvertedIndex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_InvertedIndex_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *IndexRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*WordEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_InvertedIndex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_InvertedIndex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_InvertedIndex_proto_rawDescGZIP(), []int{1}
}

func (x *IndexResponse) GetEntries() []*WordEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type WordEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Files         []*FileFrequency       `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordEntry) Reset() {
	*x = WordEntry{}
	mi := &file_InvertedIndex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordEntry) ProtoMessage() {}

func (x *WordEntry) ProtoReflect() protoreflect.Message {
	mi := &file_InvertedIndex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordEntry.ProtoReflect.Descriptor instead.
func (*WordEntry) Descriptor() ([]byte, []int) {
	return file_InvertedIndex_proto_rawDescGZIP(), []int{2}
}

func (x *WordEntry) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordEntry) GetFiles() []*FileFrequency {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileFrequency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Frequency     int32                  `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileFrequency) Reset() {
	*x = FileFrequency{}
	mi := &file_InvertedIndex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileFrequency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileFrequency) ProtoMessage() {}

func (x *FileFrequency) ProtoReflect() protoreflect.Message {
	mi := &file_InvertedIndex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileFrequency.ProtoReflect.Descriptor instead.
func (*FileFrequency) Descriptor() ([]byte, []int) {
	return file_InvertedIndex_proto_rawDescGZIP(), []int{3}
}

func (x *FileFrequency) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileFrequency) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

var File_InvertedIndex_proto protoreflect.FileDescriptor

const file_InvertedIndex_proto_rawDesc = "" +
	"\n" +
	"\x13InvertedIndex.proto\x12\rInvertedIndex\">\n" +
	"\fIndexRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"C\n" +
	"\rIndexResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.InvertedIndex.WordEntryR\aentries\"S\n" +
	"\tWordEntry\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x122\n" +
	"\x05files\x18\x02 \x03(\v2\x1c.InvertedIndex.FileFrequencyR\x05files\"I\n" +
	"\rFileFrequency\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x05R\tfrequency2Z\n" +
	"\rInvertedIndex\x12I\n" +
	"\n" +
	"BuildIndex\x12\x1b.InvertedIndex.IndexRequest\x1a\x1c.InvertedIndex.IndexResponse(\x01B\x11Z\x0f/;InvertedIndexb\x06proto3"

var (
	file_InvertedIndex_proto_rawDescOnce sync.Once
	file_InvertedIndex_proto_rawDescData []byte
)

func file_InvertedIndex_proto_rawDescGZIP() []byte {
	file_InvertedIndex_proto_rawDescOnce.Do(func() {
		file_InvertedIndex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_InvertedIndex_proto_rawDesc), len(file_InvertedIndex_proto_rawDesc)))
	})
	return file_InvertedIndex_proto_rawDescData
}

var file_InvertedIndex_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_InvertedIndex_proto_goTypes = []any{
	(*IndexRequest)(nil),  // 0: InvertedIndex.IndexRequest
	(*IndexResponse)(nil), // 1: InvertedIndex.IndexResponse
	(*WordEntry)(nil),     // 2: InvertedIndex.WordEntry
	(*FileFrequency)(nil), // 3: InvertedIndex.FileFrequency
}
var file_InvertedIndex_proto_depIdxs = []int32{
	2, // 0: InvertedIndex.IndexResponse.entries:type_name -> InvertedIndex.WordEntry
	3, // 1: InvertedIndex.WordEntry.files:type_name -> InvertedIndex.FileFrequency
	0, // 2: InvertedIndex.InvertedIndex.BuildIndex:input_type -> InvertedIndex.IndexRequest
	1, // 3: InvertedIndex.InvertedIndex.BuildIndex:output_type -> InvertedIndex.IndexResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_InvertedIndex_proto_init() }
func file_InvertedIndex_proto_init() {
	if File_InvertedIndex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_InvertedIndex_proto_rawDesc), len(file_InvertedIndex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_InvertedIndex_proto_goTypes,
		DependencyIndexes: file_InvertedIndex_proto_depIdxs,
		MessageInfos:      file_InvertedIndex_proto_msgTypes,
	}.Build()
	File_InvertedIndex_proto = out.File
	file_InvertedIndex_proto_goTypes = nil
	file_InvertedIndex_proto_depIdxs = nil
}
