// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: AnswerReceive.proto

package AnswerReceive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WordEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Files         []*FileFrequency       `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordEntry) Reset() {
	*x = WordEntry{}
	mi := &file_AnswerReceive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordEntry) ProtoMessage() {}

func (x *WordEntry) ProtoReflect() protoreflect.Message {
	mi := &file_AnswerReceive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordEntry.ProtoReflect.Descriptor instead.
func (*WordEntry) Descriptor() ([]byte, []int) {
	return file_AnswerReceive_proto_rawDescGZIP(), []int{0}
}

func (x *WordEntry) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordEntry) GetFiles() []*FileFrequency {
	if x != nil {
		return x.Files
	}
	return nil
}

type FilesCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesCount    int32                  `protobuf:"varint,2,opt,name=filesCount,proto3" json:"filesCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesCount) Reset() {
	*x = FilesCount{}
	mi := &file_AnswerReceive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesCount) ProtoMessage() {}

func (x *FilesCount) ProtoReflect() protoreflect.Message {
	mi := &file_AnswerReceive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesCount.ProtoReflect.Descriptor instead.
func (*FilesCount) Descriptor() ([]byte, []int) {
	return file_AnswerReceive_proto_rawDescGZIP(), []int{1}
}

func (x *FilesCount) GetFilesCount() int32 {
	if x != nil {
		return x.FilesCount
	}
	return 0
}

type FileFrequency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Frequency     int32                  `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileFrequency) Reset() {
	*x = FileFrequency{}
	mi := &file_AnswerReceive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileFrequency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileFrequency) ProtoMessage() {}

func (x *FileFrequency) ProtoReflect() protoreflect.Message {
	mi := &file_AnswerReceive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileFrequency.ProtoReflect.Descriptor instead.
func (*FileFrequency) Descriptor() ([]byte, []int) {
	return file_AnswerReceive_proto_rawDescGZIP(), []int{2}
}

func (x *FileFrequency) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileFrequency) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_AnswerReceive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AnswerReceive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_AnswerReceive_proto_rawDescGZIP(), []int{3}
}

func (x *UploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_AnswerReceive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_AnswerReceive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_AnswerReceive_proto_rawDescGZIP(), []int{4}
}

func (x *Query) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Matches       []*FileMatch           `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_AnswerReceive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_AnswerReceive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_AnswerReceive_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResult) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryResult) GetMatches() []*FileMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type FileMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Rank          float32                `protobuf:"fixed32,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMatch) Reset() {
	*x = FileMatch{}
	mi := &file_AnswerReceive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMatch) ProtoMessage() {}

func (x *FileMatch) ProtoReflect() protoreflect.Message {
	mi := &file_AnswerReceive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMatch.ProtoReflect.Descriptor instead.
func (*FileMatch) Descriptor() ([]byte, []int) {
	return file_AnswerReceive_proto_rawDescGZIP(), []int{6}
}

func (x *FileMatch) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMatch) GetRank() float32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

var File_AnswerReceive_proto protoreflect.FileDescriptor

const file_AnswerReceive_proto_rawDesc = "" +
	"\n" +
	"\x13AnswerReceive.proto\x12\rAnswerReceive\"S\n" +
	"\tWordEntry\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x122\n" +
	"\x05files\x18\x02 \x03(\v2\x1c.AnswerReceive.FileFrequencyR\x05files\",\n" +
	"\n" +
	"FilesCount\x12\x1e\n" +
	"\n" +
	"filesCount\x18\x02 \x01(\x05R\n" +
	"filesCount\"I\n" +
	"\rFileFrequency\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x05R\tfrequency\"*\n" +
	"\x0eUploadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1d\n" +
	"\x05Query\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"W\n" +
	"\vQueryResult\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x122\n" +
	"\amatches\x18\x02 \x03(\v2\x18.AnswerReceive.FileMatchR\amatches\";\n" +
	"\tFileMatch\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x02R\x04rank2\xe5\x01\n" +
	"\n" +
	"Dictionary\x12J\n" +
	"\x0eSendFilesCount\x12\x19.AnswerReceive.FilesCount\x1a\x1d.AnswerReceive.UploadResponse\x12K\n" +
	"\x0eSendDictionary\x12\x18.AnswerReceive.WordEntry\x1a\x1d.AnswerReceive.UploadResponse(\x01\x12>\n" +
	"\x06Search\x12\x14.AnswerReceive.Query\x1a\x1a.AnswerReceive.QueryResult(\x010\x01B\x11Z\x0f/;AnswerReceiveb\x06proto3"

var (
	file_AnswerReceive_proto_rawDescOnce sync.Once
	file_AnswerReceive_proto_rawDescData []byte
)

func file_AnswerReceive_proto_rawDescGZIP() []byte {
	file_AnswerReceive_proto_rawDescOnce.Do(func() {
		file_AnswerReceive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AnswerReceive_proto_rawDesc), len(file_AnswerReceive_proto_rawDesc)))
	})
	return file_AnswerReceive_proto_rawDescData
}

var file_AnswerReceive_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_AnswerReceive_proto_goTypes = []any{
	(*WordEntry)(nil),      // 0: AnswerReceive.WordEntry
	(*FilesCount)(nil),     // 1: AnswerReceive.FilesCount
	(*FileFrequency)(nil),  // 2: AnswerReceive.FileFrequency
	(*UploadResponse)(nil), // 3: AnswerReceive.UploadResponse
	(*Query)(nil),          // 4: AnswerReceive.Query
	(*QueryResult)(nil),    // 5: AnswerReceive.QueryResult
	(*FileMatch)(nil),      // 6: AnswerReceive.FileMatch
}
var file_AnswerReceive_proto_depIdxs = []int32{
	2, // 0: AnswerReceive.WordEntry.files:type_name -> AnswerReceive.FileFrequency
	6, // 1: AnswerReceive.QueryResult.matches:type_name -> AnswerReceive.FileMatch
	1, // 2: AnswerReceive.Dictionary.SendFilesCount:input_type -> AnswerReceive.FilesCount
	0, // 3: AnswerReceive.Dictionary.SendDictionary:input_type -> AnswerReceive.WordEntry
	4, // 4: AnswerReceive.Dictionary.Search:input_type -> AnswerReceive.Query
	3, // 5: AnswerReceive.Dictionary.SendFilesCount:output_type -> AnswerReceive.UploadResponse
	3, // 6: AnswerReceive.Dictionary.SendDictionary:output_type -> AnswerReceive.UploadResponse
	5, // 7: AnswerReceive.Dictionary.Search:output_type -> AnswerReceive.QueryResult
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AnswerReceive_proto_init() }
func file_AnswerReceive_proto_init() {
	if File_AnswerReceive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AnswerReceive_proto_rawDesc), len(file_AnswerReceive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AnswerReceive_proto_goTypes,
		DependencyIndexes: file_AnswerReceive_proto_depIdxs,
		MessageInfos:      file_AnswerReceive_proto_msgTypes,
	}.Build()
	File_AnswerReceive_proto = out.File
	file_AnswerReceive_proto_goTypes = nil
	file_AnswerReceive_proto_depIdxs = nil
}
